# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning
  logs:
    custom_components.openai_conversation_patch: debug

openai_conversation_patch:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
